[workspace]

[package]
name = "bonus"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "myapp:bonus"
target = { path = "../../wit" }

[dependencies]
wit-bindgen        = { version = "0.60.0", features = ["async", "async-spawn"] }
utoipa             = { version = "5.5.0", features = ["axum_extras"] }
utoipa-axum        = "0.2.0"
serde              = { version = "1.0.229", features = ["derive"] }
serde_json         = "1.0.151"
diesel             = { version = "2.3.11", default-features = false, features = ["postgres_backend", "chrono"] }
diesel-wasm-bridge = { path = "../../crates/diesel-wasm-bridge" }
chrono             = { version = "0.4.45", default-features = false }
thiserror          = "2.0.19"
axum               = { version = "0.8.9", features = ["json"], default-features = false }
tower              = { version = "0.5.3", default-features = false }

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
